language: rust

# We expressly write out the build matrix here because we need to set the
# appropriate target for each platform. Happily, because there's no Linux
# support yet, this is pretty easy!
rust:
  - stable
  - beta
  - nightly

env:
  - TARGET_X=x86_64-apple-darwin RELEASE=false
  - TARGET_X=x86_64-apple-darwin RELEASE=true

os:
  - osx

matrix:
  allow_failures:
    - rust: nightly

script:
  - "travis/test.sh"
