version: 1.0.{build}
os:
  - Visual Studio 2015
clone_depth: 1
configuration:
  - Debug
  - Release
platform:
  - x64
  - Win32
environment:
  matrix:
    - TOOLCHAIN_VERSION: 14.0
      RUST: 1.9.0
    - TOOLCHAIN_VERSION: 14.0
      RUST: beta
    - TOOLCHAIN_VERSION: 14.0
      RUST: nightly

    - TOOLCHAIN_VERSION: 12.0
      RUST: 1.9.0
    - TOOLCHAIN_VERSION: 12.0
      RUST: beta
    - TOOLCHAIN_VERSION: 12.0
      RUST: nightly

matrix:
  allow_failures:
    - RUST: nightly

build_script: appveyor/build.bat